### PR TITLE
Milestone-1: Project setup

### PR DESCRIPTION
**Pull request by vanheaven-ui**
This pull request includes:

- creating bin and lib directories
- adding .gitkeep file to bin empty folder.
- creating main.rb file and printing "Hello World from within"
- adding main.rb file to the bin directory
- testing with bash command ./bin/main.rb

### CODE REVIEW

**Comment by Dandush03** [comment]
# Status: 🔴 Required Changes 🔴 

Guys, in order to continue to the next milestone your `main.rb` file, should be placed as an [executable file](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/) and should have the  `#!/usr/bin/env ruby` as the top line

### But before doing any of that, don't forget that you most activate Stickler in this project. Make sure you have it set up for your next review.

### Happy Coding 💻

**Comment by 8Bts** [comment]
Thanks for your review @Dandush03. We fixed problems that you mentioned.

**Comment by lekegitrepo** [comment]
#### Hi @vanheaven-ui and @8Bts :clap: :clap:
##### Good job :+1: for implementing the required changes. This project is approved.

### _Reviewed by Temitayo Adeleke_.

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved

**Pull request merged**
